import{i,S as l}from"./assets/vendor-0fc460d7.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const a of e.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function r(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function s(t){if(t.ep)return;t.ep=!0;const e=r(t);fetch(t.href,e)}})();async function u(o,n=1){const t=`https://pixabay.com/api/?key=44189904-4675a190af98c4e4efc911d57&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=12`;try{const e=await fetch(t);if(!e.ok)throw new Error("Failed to fetch images");return e.json()}catch(e){throw console.error("Error fetching images:",e),e}}function d(o){const n=document.querySelector(".gallery");n.innerHTML=o.map(r=>`
    <a href="${r.largeImageURL}" class="gallery__item">
      <img src="${r.webformatURL}" alt="${r.tags}" class="gallery__image" />
      <div class="info">
        <p class="info-item">Likes: <span>${r.likes}</span></p>
        <p class="info-item">Views: <span>${r.views}</span></p>
        <p class="info-item">Comments: <span>${r.comments}</span></p>
        <p class="info-item">Downloads: <span>${r.downloads}</span></p>
      </div>
    </a>
  `).join("")}function f(){document.querySelector(".gallery").innerHTML=""}function p(){const o=document.querySelector(".loader");o.style.display="block"}function m(){const o=document.querySelector(".loader");o.style.display="none"}document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector(".form"),n=o.querySelector('input[name="query"]');let r;o.addEventListener("submit",async s=>{s.preventDefault();const t=n.value.trim();if(t===""){i.error({title:"Error",message:"Please enter a search term"});return}f(),p();try{const e=await u(t);e.hits.length===0?i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(d(e.hits),r?r.refresh():(r=new l(".gallery a",{captions:!0,captionDelay:0}),r.on("show.simplelightbox",function(){const a=r.currentImageIndex,c=`<div class="slbCaptionOuter">${e.hits[a].tags}</div>`;document.querySelector(".slbInner").insertAdjacentHTML("beforeend",c)}),r.on("close.simplelightbox",function(){document.querySelector(".slbCaptionOuter").remove()})))}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{m()}})});
//# sourceMappingURL=commonHelpers.js.map
