import{i,S as u}from"./assets/vendor-0fc460d7.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))a(t);new MutationObserver(t=>{for(const e of t)if(e.type==="childList")for(const n of e.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&a(n)}).observe(document,{childList:!0,subtree:!0});function r(t){const e={};return t.integrity&&(e.integrity=t.integrity),t.referrerPolicy&&(e.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?e.credentials="include":t.crossOrigin==="anonymous"?e.credentials="omit":e.credentials="same-origin",e}function a(t){if(t.ep)return;t.ep=!0;const e=r(t);fetch(t.href,e)}})();async function f(s,o=1){const t=`https://pixabay.com/api/?key=44189904-4675a190af98c4e4efc911d57&q=${encodeURIComponent(s)}&image_type=photo&orientation=horizontal&safesearch=true&page=${o}&per_page=12`;try{const e=await fetch(t);if(!e.ok)throw new Error("Failed to fetch images");return e.json()}catch(e){throw console.error("Error fetching images:",e),e}}function d(s){const o=document.querySelector(".gallery");o.innerHTML=s.map(r=>`
    <a href="${r.largeImageURL}" class="gallery__item">
      <img src="${r.webformatURL}" alt="${r.tags}" class="gallery__image" />
      <div class="info">
        <p class="info-item">Likes: <span>${r.likes}</span></p>
        <p class="info-item">Views: <span>${r.views}</span></p>
        <p class="info-item">Comments: <span>${r.comments}</span></p>
        <p class="info-item">Downloads: <span>${r.downloads}</span></p>
      </div>
    </a>
  `).join("")}function p(){document.querySelector(".loader").style.display="block"}function m(){document.querySelector(".loader").style.display="none"}function y(){document.querySelector(".gallery").innerHTML=""}document.addEventListener("DOMContentLoaded",()=>{const s=document.querySelector(".form"),o=s.querySelector('input[name="query"]');let r;s.addEventListener("submit",async a=>{a.preventDefault();const t=o.value.trim();if(t===""){i.error({title:"Error",message:"Please enter a search term"});return}y(),p();try{const e=await f(t);e.hits.length===0?i.info({title:"Info",message:"Sorry, there are no images matching your search query. Please try again!"}):(d(e.hits),r?r.refresh():(r=new u(".gallery a",{captions:!0,captionDelay:0}),r.on("show.simplelightbox",function(){const n=document.querySelector(".slbInner"),c=r.currentImageIndex,l=`<div class="slbCaptionOuter">${e.hits[c].tags}</div>`;n.insertAdjacentHTML("beforeend",l)}),r.on("close.simplelightbox",function(){const n=document.querySelector(".slbCaptionOuter");n&&n.remove()})))}catch{i.error({title:"Error",message:"Failed to fetch images. Please try again later."})}finally{m()}})});
//# sourceMappingURL=commonHelpers.js.map
