import{i as c,S as l}from"./assets/vendor-0fc460d7.js";(function(){const n=document.createElement("link").relList;if(n&&n.supports&&n.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))s(e);new MutationObserver(e=>{for(const r of e)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function t(e){const r={};return e.integrity&&(r.integrity=e.integrity),e.referrerPolicy&&(r.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?r.credentials="include":e.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(e){if(e.ep)return;e.ep=!0;const r=t(e);fetch(e.href,r)}})();const f="44189904-4675a190af98c4e4efc911d57";async function u(o,n=1){const s=`https://pixabay.com/api/?key=${f}&q=${encodeURIComponent(o)}&image_type=photo&orientation=horizontal&safesearch=true&page=${n}&per_page=12`;try{const e=await fetch(s);if(!e.ok)throw new Error("Failed to fetch images");return e.json()}catch(e){throw console.error("Error fetching images:",e),e}}function d(o){const n=document.querySelector(".gallery");n.innerHTML=o.map(t=>`
    <a href="${t.largeImageURL}" class="gallery__item">
      <img src="${t.webformatURL}" alt="${t.tags}" class="gallery__image" />
      <div class="info">
        <p class="info-item">Likes: <span>${t.likes}</span></p>
        <p class="info-item">Views: <span>${t.views}</span></p>
        <p class="info-item">Comments: <span>${t.comments}</span></p>
        <p class="info-item">Downloads: <span>${t.downloads}</span></p>
      </div>
    </a>
  `).join("")}function p(){document.querySelector(".loader").style.display="block"}function m(){document.querySelector(".loader").style.display="none"}function y(){document.querySelector(".gallery").innerHTML=""}function i(o){c.error({title:"Error",message:o})}function h(o){c.info({title:"Info",message:o})}document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector(".form"),n=o.querySelector('input[name="query"]');let t;o.addEventListener("submit",async s=>{s.preventDefault();const e=n.value.trim();if(e===""){i("Please enter a search term");return}y(),p();try{const r=await u(e);r.hits.length===0?h("Sorry, there are no images matching your search query. Please try again!"):(d(r.hits),t||(t=new l(".gallery a",{captions:!0,captionDelay:0})),t.refresh())}catch{i("Failed to fetch images. Please try again later.")}finally{m()}})});
//# sourceMappingURL=commonHelpers.js.map
